### ISSUE TITLE
Get medal images from the pogo wiki

### ISSUE THREAD

**Issue by ccev** [na-ji/leaderboard#489]
They're all properly colored there!

You can view them [here](https://pokemongo.fandom.com/wiki/Medals). Full res for them is at `https://static.wikia.nocookie.net/pokemongo/images/8/86/Collector_Gold.png`

**Comment by na-ji** [comment]
I noticed that the colors are off compared to the real ones. This is the main reason I haven't used them yet.

**Comment by ccev** [comment]
i noticed that too, but it's a lot better than bright green colors

**Comment by na-ji** [comment]
Good point
